---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      l
        resources: {}
---
